# Generated by Django 5.0.1 on 2024-02-13 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0006_alter_department_department_alter_farm_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_workshop', to='farm.farm')),
            ],
            options={
                'verbose_name': 'Workshop',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.UniqueConstraint(models.F('name'), models.F('farm'), name='unique_farm_workshop_name'),
        ),
    ]
