# Generated by Django 5.0.1 on 2024-02-13 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0006_alter_department_department_alter_farm_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Fleet Category',
                'verbose_name_plural': 'Fleet Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='vehicle.fleetcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Fleet',
                'verbose_name_plural': 'Fleets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('type', models.CharField(choices=[('1', 'Tractor'), ('2', 'Harvester'), ('3', 'Truck'), ('4', 'Car'), ('5', 'Agricultural Implement'), ('6', 'Agricultural Machine'), ('0', 'Other')], max_length=3, verbose_name='Type')),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Manufacture')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Serial Number')),
                ('plate', models.CharField(max_length=15, verbose_name='Plate')),
                ('hour_meter', models.CharField(blank=True, max_length=15, null=True, verbose_name='Hour Meter')),
                ('mileage', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mileage')),
                ('status', models.CharField(choices=[('1', 'Operational'), ('2', 'Under Maintenance'), ('3', 'Awaiting Parts'), ('4', 'Out of Service'), ('5', 'Active'), ('6', 'Inactive'), ('7', 'In Maintenance'), ('0', 'Other')], max_length=3, verbose_name='Status')),
                ('color', models.CharField(choices=[('1', 'Black'), ('2', 'White'), ('3', 'Silver'), ('4', 'Gray'), ('5', 'Red'), ('6', 'Blue'), ('7', 'Green'), ('8', 'Yellow'), ('9', 'Orange'), ('10', 'Purple'), ('11', 'Brown'), ('12', 'Pink'), ('13', 'Beige'), ('14', 'Gold'), ('15', 'Other')], max_length=3, verbose_name='Color')),
                ('brand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.brand', verbose_name='Brand')),
                ('farm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='farm.farm', verbose_name='Farm')),
                ('fleet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.fleet', verbose_name='Fleet')),
                ('model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.vehiclemodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Maintenance Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance History',
                'verbose_name_plural': 'Maintenance Histories',
            },
        ),
    ]
