# Generated by Django 5.0.1 on 2024-01-28 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('zipcode', models.CharField(blank=True, max_length=9, null=True, verbose_name='Zip Code')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Neighborhood')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_city', to='address.city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='State')),
                ('acronym', models.CharField(max_length=2, unique=True, verbose_name='Acronym')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_uf', to='address.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_city', to='address.uf'),
        ),
        migrations.AddConstraint(
            model_name='uf',
            constraint=models.UniqueConstraint(models.F('name'), models.F('acronym'), name='unique_uf_name_acronym'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(models.F('name'), models.F('uf'), name='unique_uf_city'),
        ),
    ]
