# Generated by Django 5.0.1 on 2024-01-31 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'Others'), ('1', 'Active'), ('2', 'Suspended'), ('3', 'Inactive'), ('4', 'Vacation'), ('5', 'Away')], max_length=100, null=True, verbose_name='Status')),
                ('department', models.ManyToManyField(related_name='department_employee', to='farm.department', verbose_name='Department')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_person', to='person.person', verbose_name='Employee')),
                ('position', models.ManyToManyField(related_name='position_employee', to='employee.position', verbose_name='Position')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
