# Generated by Django 5.0.1 on 2024-02-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-created_at'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_person', to='person.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=200, unique=True, verbose_name='Position'),
        ),
    ]
