# Generated by Django 5.0.1 on 2024-02-04 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_position_options_and_more'),
        ('farm', '0005_alter_farm_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='department_employee', to='farm.department', verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='position_employee', to='employee.position', verbose_name='Position'),
            preserve_default=False,
        ),
    ]
