# Generated by Django 5.0.1 on 2024-02-04 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_department_remove_employee_position_and_more'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_person', to='person.person', verbose_name='Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('0', 'Others'), ('1', 'Active'), ('2', 'Suspended'), ('3', 'Inactive'), ('4', 'Vacation'), ('5', 'Away')], default=None, max_length=100, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
