# Generated by Django 5.0.1 on 2024-02-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_person_alter_employee_status'),
        ('farm', '0005_alter_farm_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='farm',
            field=models.ForeignKey(default='fee4e5ce-17c0-438f-90be-4699c03a3012', on_delete=django.db.models.deletion.CASCADE, related_name='farm_employee', to='farm.farm', verbose_name='Farm'),
            preserve_default=False,
        ),
    ]
