# Generated by Django 5.0.1 on 2024-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('0', 'Others'), ('1', 'Active'), ('2', 'Suspended'), ('3', 'Inactive'), ('4', 'Vacation'), ('5', 'Away')], max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=50, unique=True, verbose_name='Position'),
        ),
    ]
