# Generated by Django 5.0.1 on 2024-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.CharField(default=1, max_length=200, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
