# Generated by Django 5.0.1 on 2024-02-03 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_department_department_alter_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_farm', to='farm.farm', verbose_name='Farm'),
        ),
    ]
