# Generated by Django 5.0.1 on 2024-02-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_remove_farm_departments_department_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='farm',
        ),
        migrations.AddField(
            model_name='farm',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments', to='farm.department', verbose_name='Department'),
        ),
    ]
