# Generated by Django 5.0.1 on 2024-02-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_department_farm_farm_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='departments',
            field=models.ManyToManyField(related_name='departments', to='farm.department', verbose_name='Department'),
        ),
    ]
