# Generated by Django 5.0.1 on 2024-01-28 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('document', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Document CPF/CNPJ')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('addresses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_addresses', to='address.address')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('type', models.CharField(choices=[('0', 'Other'), ('1', 'Personal'), ('2', 'Commercial'), ('3', 'Emergency'), ('4', 'Primary'), ('5', 'Secondary'), ('6', 'Residential'), ('7', 'Cellular'), ('8', 'Work'), ('9', 'Message')], default='1', max_length=14, verbose_name='E-mail Type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_email', to='person.person')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Number contact')),
                ('type', models.CharField(choices=[('0', 'Other'), ('1', 'Personal'), ('2', 'Commercial'), ('3', 'Emergency'), ('4', 'Primary'), ('5', 'Secondary'), ('6', 'Residential'), ('7', 'Cellular'), ('8', 'Work'), ('9', 'Message')], default='1', max_length=2, verbose_name='Phone Type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_phone', to='person.person')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(models.F('name'), models.F('document'), name='unique_name_document'),
        ),
    ]
